### ISSUE TITLE
Compiling Faiss library for iOS

### ISSUE THREAD

**Issue by Aashit-Sharma** [szanni/ios-autotools#2]
Hi ,I wanted to know whether it is possible to compile the FAISS library (https://github.com/facebookresearch/faiss) for iOS using your tools 

And if it is , should we expect performance reduction ?

Currently Faiss only has compile options for linux and Mac

Thanks !

**Comment by szanni** [comment]
Hi,
well the FAISS library contains a simple Makefile, so it should be possible to just compile it  via the external build mechanism (File > New > Target > OS X > Other > External Build System).
A bigger challenge might be compiling the BLAS library, which FAISS seems to depend on.
And there would definitely be a performance reduction. Math heavy operations and mobile devices don't tend mix well.
So no need for the ios-autotools as far as I can see.
Best
