### ISSUE TITLE
No configure script found

### ISSUE THREAD

**Issue by kvaDrug** [szanni/ios-autotools#3]
Hi! Thanks for the tool! I'm trying to build libarchive for iOS. I've added autoframework and iconfigure to the libarchive folder, now I'm running:
`./autoframework libarchive_ libarchive.a`
And receive error:
```
make: *** No rule to make target 'distclean'.  Stop.
No configure script found.
```
Probably I don't quite understand how to use the script. Can you please explain, what is the configure file?

**Comment by szanni** [comment]
Well, it gives you the error right there:
`No configure script found.`

Not sure what your setup is, building libarchive from a dist package or git. The tool itself works as intended.

You can try to see if running `autoreconf --install` resolves the issue.
I would highly recommend looking at the Autotools Mythbuster guide for a good introduction to autotools.
